-- Run with a role permitted to create these objects. Existing data is preserved.
CREATE WAREHOUSE IF NOT EXISTS ROOTWATCH_WH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS ROOTWATCH;
CREATE SCHEMA IF NOT EXISTS ROOTWATCH.PUBLIC;
USE WAREHOUSE ROOTWATCH_WH;
USE DATABASE ROOTWATCH;
USE SCHEMA PUBLIC;
CREATE TABLE IF NOT EXISTS SERVER_LOGS (
    ID VARCHAR NOT NULL, "TIMESTAMP" TIMESTAMP_TZ NOT NULL,
    SERVICE VARCHAR NOT NULL, ENDPOINT VARCHAR NOT NULL, METHOD VARCHAR NOT NULL,
    STATUS_CODE INTEGER NOT NULL, LATENCY_MS FLOAT NOT NULL,
    ERROR_TYPE VARCHAR, ERROR_MESSAGE VARCHAR, DEPLOYMENT_VERSION VARCHAR NOT NULL,
    REQUEST_ID VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS INCIDENTS (
    INCIDENT_ID VARCHAR NOT NULL, SERVICE VARCHAR NOT NULL, ENDPOINT VARCHAR NOT NULL,
    METHOD VARCHAR NOT NULL, ERROR_TYPE VARCHAR NOT NULL, STATUS VARCHAR NOT NULL,
    START_TIME TIMESTAMP_TZ NOT NULL, LAST_SEEN TIMESTAMP_TZ NOT NULL,
    OCCURRENCE_COUNT INTEGER NOT NULL, FAILURE_RATE FLOAT NOT NULL, SEVERITY VARCHAR NOT NULL,
    DEPLOYMENT_VERSION VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS DEPLOYMENTS (
    DEPLOYMENT_VERSION VARCHAR NOT NULL, DEPLOYED_AT TIMESTAMP_TZ NOT NULL,
    COMMIT_HASH VARCHAR, FILES_CHANGED VARIANT, DESCRIPTION VARCHAR
);
